inherit_gem:
  jekyll: .rubocop.yml

AllCops:
  Exclude:
    - lib/jekyll-admin/public/**/*
    - src/**/*
    - node_modules/**/*
    - Gemfile
    - jekyll-admin.gemspec
Metrics/AbcSize:
  Max: 22
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 21
Metrics/PerceivedComplexity:
  Max: 9
