title: Jekyll Manager
description: A repackaged Jekyll Admin fork with some alterations.
collections:
  frontend:
    permalink: /frontend/:path/
    output: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

baseurl: "/jekyll-manager"
